# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_productdetail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cart_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductDetail')),
            ],
        ),
    ]
