# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdetail_slug'),
        ('cart', '0002_remove_usercart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='usercart',
            name='cart_items',
            field=models.ManyToManyField(to='product.ProductDetail'),
        ),
    ]
