# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180317_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='cart_items',
            new_name='cartname',
        ),
    ]
