# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_productdetail_slug'),
        ('cart', '0006_auto_20180317_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='usercart',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ProductDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
