# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_usercart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
