# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20180318_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='cart_item',
            new_name='cartitem',
        ),
    ]
