# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('types', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
