# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180313_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
